import braidsImg from "../../../public/braids.jpeg";
import smokebraidsImg from "../../../public/smoke_braids.jpeg";

const forAll = [
  {
    id: 1,
    imgSrc: braidsImg,
    title: "Retwist",
    price: 80,
    time: 240,
    Type: "For All",
    avail: [1, 3, 5],
  },
  {
    id: 2,
    imgSrc: smokebraidsImg,
    title: " Barrel Twist",
    price: 60,
    time: 180,
    Type: "For All",
    avail: [1, 3, 5],
  },
  {
    id: 3,
    imgSrc: braidsImg,
    title: "Men's Cornrows",
    price: 30,
    time: 120,
    Type: "For All",
    avail: [1, 3, 5],
  },
  {
    id: 4,
    imgSrc: braidsImg,
    title: "Mens Twist",
    price: 40,
    time: 180,
    Type: "For All",
    avail: [1, 3, 5],
  },
  {
    id: 5,
    imgSrc: braidsImg,
    title: "Natural Single Braids",
    price: 50,
    time: 240,
    Type: "For All",
    avail: [1, 3, 5],
  },
  {
    id: 6,
    imgSrc: braidsImg,
    title: "Half Braids Half Cornrow",
    price: 45,
    time: 180,
    Type: "For All",
    avail: [1, 3, 5],
  },
];
const LadiesTwists = [
  {
    id: 1,
    imgSrc: braidsImg,
    title: "Passion Twists",
    price: 120,
    time: 300,
    Type: "Ladies Twists",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    imgSrc: braidsImg,
    title: "Island twists/Goddess Twists",
    price: 135,
    time: 360,
    Type: "Ladies Twists",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    imgSrc: braidsImg,
    title: "Kinky Spring Twist",
    price: 130,
    time: 360,
    Type: "Ladies Twists",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 4,
    imgSrc: braidsImg,
    title: "Thick Kinky Twists",
    price: 100,
    time: 270,
    Type: "Ladies Twists",
    avail: [1, 2, 3, 4, 5],
  },
];
const Braids = [
  {
    id: 1,
    imgSrc: braidsImg,
    title: "Small/Xtra Small Knotless Braids",
    price: 180,
    time: 540,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    imgSrc: braidsImg,
    title: "Medium Knotless Braids",
    price: 155,
    time: 480,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    imgSrc: braidsImg,
    title: " Jumbo Knotless Braids",
    price: 115,
    time: 240,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 4,
    imgSrc: braidsImg,
    title: " Small Traditional Box Braids",
    price: 160,
    time: 480,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 5,
    imgSrc: braidsImg,
    title: " Medium Traditional Box Braids",
    price: 140,
    time: 360,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 6,
    imgSrc: braidsImg,
    title: " Knotless Bob",
    price: 130,
    time: 510,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 7,
    imgSrc: braidsImg,
    title: " Goddess/Boho Knotless Braids",
    price: 160,
    time: 510,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 8,
    imgSrc: braidsImg,
    title: " French Curls",
    price: 190,
    time: 540,
    Type: "Braids",
    avail: [1, 2, 3, 4, 5],
  },
];
const Locs = [
  {
    id: 1,
    imgSrc: braidsImg,
    title: "Butterfly Locs",
    price: 130,
    time: 360,
    Type: "Locs",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    imgSrc: braidsImg,
    title: "SoftLocs",
    price: 130,
    time: 360,
    Type: "Locs",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    imgSrc: braidsImg,
    title: " Microlocs Install",
    price: 450,
    time: 600,
    Type: "Locs",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 4,
    imgSrc: braidsImg,
    title: "Microloc Maintenance/ Retightening",
    price: 100,
    time: 300,
    Type: "Locs",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 5,
    imgSrc: braidsImg,
    title: "Loc Rewrapping",
    price: 35,
    time: 90,
    Type: "Locs",
    avail: [1, 3, 5],
  },
  {
    id: 6,
    imgSrc: braidsImg,
    title: "Butterfly Locs",
    price: 130,
    time: 360,
    Type: "Locs",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 7,
    imgSrc: braidsImg,
    title: "Foreign Loc Removal",
    price: 40,
    time: 120,
    Type: "Locs",
    avail: [1, 3, 5],
  },
];
const Halfs = [
  {
    id: 1,
    imgSrc: braidsImg,
    title: " Diva/Geometric Braids",
    price: 150,
    time: 420,
    Type: "Half & Half",
    avail: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    imgSrc: braidsImg,
    title: "Fulani Braids",
    price: 140,
    time: 300,
    Type: "Half & Half",
    avail: [1, 2, 3, 4, 5],
  },
];
export const styleData = [forAll, LadiesTwists, Braids, Halfs, Locs];
